jenkins

diff --git a/11-frontend/CD/Jenkinsfile b/11-frontend/CD/Jenkinsfile
--- a/11-frontend/CD/Jenkinsfile
+++ b/11-frontend/CD/Jenkinsfile
@@ -28,43 +28,46 @@ pipeline {
         choice(name: 'Deploy_to', choices: ['dev', 'qa', 'prod'] ,description: 'Please choose the environemnt' )
     }
 
-    stage('Deploy') {
-        steps {
-            dir('11-frontend/CD') {
-                script {
-                    withAWS(region: 'us-east-1', credantials: 'aws-auth') {
-                        try {
-                            sh """
-                                kubectl ekd update-kubeconfig --region ${region} --name ${project}-${env_name}-eks
+    stages{
 
-                                kubectl get nodes
+        stage('Deploy') {
+            steps {
+                dir('11-frontend/CD') {
+                    script {
+                        withAWS(region: 'us-east-1', credantials: 'aws-auth') {
+                            try {
+                                sh """
+                                    kubectl ekd update-kubeconfig --region ${region} --name ${project}-${env_name}-eks
 
-                                cd ${component}-helm
+                                    kubectl get nodes
 
-                                sed -i "s/IMAGE_VERSION/${params.image_version}/g" values-${params.Deploy_to}
+                                    cd ${component}-helm
 
-                                helm upgrade --install ${component}-chart -n ${namespace} -f values-${params.Deploy_to}.
-                            """
-                        }
+                                    sed -i "s/IMAGE_VERSION/${params.image_version}/g" values-${params.Deploy_to}
 
-                        catch (err) {
-                            echo "Helm upgrade is failed, Rollback to previous version" 
+                                    helm upgrade --install ${component}-chart -n ${namespace} -f values-${params.Deploy_to}.
+                                """
+                            }
 
-                            sh """
-                                helm rollback ${component}-chart -n ${namespace}
-                                sleep 30
-                            """
+                            catch (err) {
+                                echo "Helm upgrade is failed, Rollback to previous version" 
 
-                            def rolloutStatus = sh(
-                                script: "kubectl get deployments/${component} -n ${namespace} || echo FAILED",
-                                returnStdout: true
-                            ).trim()
+                                sh """
+                                    helm rollback ${component}-chart -n ${namespace}
+                                    sleep 30
+                                """
 
-                            if (rolloutStatus.contains("successfully rolled out")) {
-                                echo "Helm upgrade failed and rollbacked to previous version"
-                                error "Helm Upgarde. Please look into it"
-                            } else {
-                                error "Helm upgrade failed and helm rollback also failed"
+                                def rolloutStatus = sh(
+                                    script: "kubectl get deployments/${component} -n ${namespace} || echo FAILED",
+                                    returnStdout: true
+                                ).trim()
+
+                                if (rolloutStatus.contains("successfully rolled out")) {
+                                    echo "Helm upgrade failed and rollbacked to previous version"
+                                    error "Helm Upgarde. Please look into it"
+                                } else {
+                                    error "Helm upgrade failed and helm rollback also failed"
+                                }
                             }
                         }
                     }
