jenkins

diff --git a/01-mongodb/CD/Jenkinsfile b/01-mongodb/CD/Jenkinsfile
--- a/01-mongodb/CD/Jenkinsfile
+++ b/01-mongodb/CD/Jenkinsfile
@@ -14,10 +14,10 @@ pipeline {
         label = 'agent-1-label'
     }
     options {
-        ansiColour('xtrem')
-        timeout(time: 40, uints: 'MINUTES')
+        ansiColor('xtrem')
+        timeout(time: 40, units: 'MINUTES')
         disableConcurrentBuilds()
-        timestamp()
+        timestamps()
     }
 
     parameters {
@@ -27,46 +27,48 @@ pipeline {
 
     stages {
         stage('Deploy into k8') {
-            script {
-                withAWS(region: 'us-east', credentails: 'aws-auth' ) {
-                    try {
-                        sh """
-                            echo "Setting up kubeconfig"
-                            aws eks update-kubeconfig --region ${region} --name expense-${params.environment}
+            steps {
+                script {
+                    withAWS(region: 'us-east', credentails: 'aws-auth' ) {
+                        try {
+                            sh """
+                                echo "Setting up kubeconfig"
+                                aws eks update-kubeconfig --region ${region} --name expense-${params.environment}
 
-                            echo "Checking cluster nodes"
-                            kubectl get nodes
+                                echo "Checking cluster nodes"
+                                kubectl get nodes
 
-                            echo "Preparing Helm deployment..."
-                            cd 01-mongodb/CD/mongodb-helm
-                            sed -i "s/IMAGE_VERSION/${params.image_version}/g" values-${params.environment}.yaml
+                                echo "Preparing Helm deployment..."
+                                cd 01-mongodb/CD/mongodb-helm
+                                sed -i "s/IMAGE_VERSION/${params.image_version}/g" values-${params.environment}.yaml
 
-                            echo "Deploying new version with Helm..."
-                            helm upgrade --intsall ${component}-chart -n ${namespace} -f values-${params.environment}.yaml
+                                echo "Deploying new version with Helm..."
+                                helm upgrade --intsall ${component}-chart -n ${namespace} -f values-${params.environment}.yaml
 
-                        """
-                    } catch (err) {
-                        echo "Helm upgare failed. Atempting rollback"
-                        echo "Rollback to previews version"
+                            """
+                        } catch (err) {
+                            echo "Helm upgare failed. Atempting rollback"
+                            echo "Rollback to previews version"
 
-                        sh """
-                            helm rollback ${component}-chart -n ${namespace}
-                            sleep 30 # wait for pods to stabilize
-                        """
-                        // Check rollout status after rollback
-                        def rolloutStatus = sh(
-                        script: "kubectl rollout status deployment/${COMPONENT} -n ${PROJECT} || echo FAILED",
-                        returnStdout: true
-                        ).trim()
+                            sh """
+                                helm rollback ${component}-chart -n ${namespace}
+                                sleep 30 # wait for pods to stabilize
+                            """
+                            // Check rollout status after rollback
+                            def rolloutStatus = sh(
+                            script: "kubectl rollout status deployment/${COMPONENT} -n ${PROJECT} || echo FAILED",
+                            returnStdout: true
+                            ).trim()
 
-                        if (rolloutStatus.contains("successfully rolled out")) {
-                        echo "Rollback succeeded. But pipeline will fail to notify issue with new release."
-                        error("New deployment failed, rollback successful. Please check the new version.")
-                        } else {
-                            error("Rollback also failed. Previous version is not running.")
-                        }
+                            if (rolloutStatus.contains("successfully rolled out")) {
+                            echo "Rollback succeeded. But pipeline will fail to notify issue with new release."
+                            error("New deployment failed, rollback successful. Please check the new version.")
+                            } else {
+                                error("Rollback also failed. Previous version is not running.")
+                            }
 
-                    }              
+                        }              
+                    }
                 }
             }
         }
